mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
    path('',include('polls.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name ='polls'

urlpatterns = [
  path('',views.IndexView.as_view(),name='index'),
  path('<int:pk>/', views.DetailView.as_view(), name='detail'),
  path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
  path('<int:question_id>/vote/', views.vote, name='vote'),
  path('realsimulation/',views.realsimulation,name='real'),
  path('fanda/',views.fandamentals,name='fanda')
]

toppage/urls.py
from django.urls import path, include
# ↓"."は同じフォルダの中のという意味
#"urlpatterns"の"Index"と"Detail"は、viewから持ってきている
from . import views

app_name ='toppage'

urlpatterns = [
    # パスの後ろに何も文字がなければ、viewsのIndexページに飛ばす
    path('', views.index),
    path('test/', views.test,name='test')
]

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
  question_text = models.CharField(max_length=200)
  pub_date = models.DateTimeField('date published')
  def __str__(self):
        return self.question_text
  def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
  question = models.ForeignKey(Question,on_delete=models.CASCADE)
  choice_text = models.CharField(max_length=200)
  votes = models.IntegerField(default=0)
  def __str__(self):
        return self.choice_text
# それぞれdjango.db.models.Modelのサブクラス
# charfield⇢文字のフィールド
# datetimefield⇢日時フィールド
# ForeignKey⇢外部キー
class Stock(models.Model):
      datetime=models.DateTimeField()

class  Realsimulation(models.Model):
      id = models.IntegerField(primary_key=True) 
      date = models.DateTimeField()
      open = models.FloatField(null=True,blank=True)
      high = models.FloatField(null=True,blank=True)
      low = models.FloatField(null=True,blank=True)
      close = models.FloatField(null=True,blank=True)
      volume = models.IntegerField(null=True,blank=True)
      currency = models.IntegerField(null=True,blank=True)
      code = models.CharField(max_length=255)
      rsi = models.FloatField(null=True,blank=True)
      days50 = models.FloatField(null=True,blank=True)
      days150 = models.FloatField(null=True,blank=True)
      days200 = models.FloatField(null=True,blank=True)
      weeks20 = models.FloatField(null=True,blank=True)
      stdev = models.FloatField(null=True,blank=True)
      bb = models.FloatField(null=True,blank=True)
      def __str__(self):
            return self.code

class  Realsimulationchoice(models.Model):
      id = models.IntegerField() 
      date = models.DateTimeField()
      open = models.FloatField(null=True,blank=True)
      high = models.FloatField(null=True,blank=True)
      low = models.FloatField(null=True,blank=True)
      close = models.FloatField(null=True,blank=True)
      volume = models.IntegerField(null=True,blank=True)
      currency = models.IntegerField(null=True,blank=True)
      code = models.CharField(max_length=255,primary_key=True)
      rsi = models.FloatField(null=True,blank=True)
      days50 = models.FloatField(null=True,blank=True)
      days150 = models.FloatField(null=True,blank=True)
      days200 = models.FloatField(null=True,blank=True)
      weeks20 = models.FloatField(null=True,blank=True)
      stdev = models.FloatField(null=True,blank=True)
      bb = models.FloatField(null=True,blank=True)
      fandaid = models.ForeignKey("Fandamental",db_column='code',on_delete=models.CASCADE)
      def __str__(self):
            return self.code

class Fandamental(models.Model):
      id = models.IntegerField() 
      meigara = models.CharField(max_length=255)
      code = models.CharField(max_length=255,primary_key=True)
      uriagetuuki1 = models.FloatField(null=True,blank=True)
      uriagetuuki2 = models.FloatField(null=True,blank=True)
      riekituuki1 = models.FloatField(null=True,blank=True)
      riekituuki2 = models.FloatField(null=True,blank=True)
      epstuuki1 = models.FloatField(null=True,blank=True)
      epstuuki2 = models.FloatField(null=True,blank=True)
      uriageshihanki1 =models.FloatField(null=True,blank=True)
      uriageshihanki2 =models.FloatField(null=True,blank=True)
      uriageshihanki3 =models.FloatField(null=True,blank=True)
      riekishihanki1 =models.FloatField(null=True,blank=True)
      riekishihanki2 =models.FloatField(null=True,blank=True)
      riekishihanki3 =models.FloatField(null=True,blank=True)
      epsshihanki1 =models.FloatField(null=True,blank=True)
      epsshihanki2 =models.FloatField(null=True,blank=True)
      epsshihanki3 =models.FloatField(null=True,blank=True)

toppage/models.py
from django.db import models

# Create your models here.

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .models import Question, Choice, Realsimulation,Fandamental
from django.template import loader
from django.urls import reverse
from django.views import generic
from io import TextIOWrapper,StringIO
from django.db.models import F
import csv

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question

class ResultsView(generic.DetailView):
    model = Question
    template_name =  "polls/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    
def realsimulation(request):
    
    stock = Realsimulation.objects.order_by("-date")[:12]

    condition = {
        'date':stock[0].date,
        'close__gt':F('bb'),
        'days150__gt':F('days200')
    }
    datas = Realsimulation.objects.all().filter(**condition)

    return render(request,"polls/real.html",{'datas': datas})

def fandamentals(request):

    condition = {
        'riekishihanki1__gt':100,
        'riekishihanki2__gt':100,
        'riekituuki1__gt':100,
        'riekituuki2__gt':100,
    }
    datas = Fandamental.objects.all().filter(**condition)
    data_count = datas.count()

    return render(request,"polls/fanda.html",{'datas': datas,'data_count':data_count})

toppage/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.template.response import TemplateResponse

def index(request):
  return TemplateResponse(request,'toppage/index.html')
# Create your views here.

def test(request):
  return TemplateResponse(request,'toppage/test.html')

polls/templates/polls/fanda.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ファンダメンタル</title>
</head>
<body>
<h3>ファンだ抽出</h3>

  <h3>直近四半期利益+100%超え</h3>
  <p>{{ data_count }}件見つかりました。</p>
  <table>
    <tr>
      <th>コード</th>
      <th>銘柄名</th>
      <th>直近四半期利益上昇率(%)</th>
      <th>前々四半期利益上昇率(%)</th>
    </tr>
    {% for data in datas %}
    <tr>
      <th><a href="#">{{data.code}}</a></th>
      <th>{{data.meigara}}</th>
      <th>{{data.riekishihanki1}}</th>
      <th>{{data.riekishihanki2}}</th>
    </tr>
    {% endfor %}
  </table>




</html>
</body>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/question_detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/real.html
{% extends "toppage/base.html" %}
{% block main %}
<h4>リアルシミュレーションで条件に当てはまった銘柄を抽出</h4>

  <p>ボリバン+2σにタッチ</p>
  <table>
    <tr>
      <th>コード</th>
      <th>終値</th>
      <th>ボリバン2σ</th>
    </tr>
    {% for data in datas %}
    <tr>
      <th><a href="#">{{data.code}}</a></th>
      <th>{{data.close}}</th>
      <th>{{data.bb}}</th>
    </tr>
    {% endfor %}
  </table>

{% endblock %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/upload.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>upload</title>
</head>
<body>
<h3>アップロードするよ</h3>
<form action="{% url 'polls:upload' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="file" class="dropify" data-default-file="ファイルを選択してください" name="csv">
  <button type="submit" class="btn" name="button">アップロード</button>
</form>
</html>
</body>

toppage/templates/toppage/base.html
<!doctype HTML>
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/">弥富投資分析サイト</a>
        </nav>
        <div class="container mt-4">
        {% block main %}
        <p>※コンテンツがありません。</p>
        {% endblock %}
        </div>
    </body>
</html>

toppage/templates/toppage/index.html
{% extends "toppage/base.html" %}

{% block main %}
トップページです。
<a href="{% url 'polls:real' %}" >リアルタイムシミュレーション</a>
<a href="{% url 'polls:fanda' %}" >ファンダメンタルズ</a>
<a href="{% url 'toppage:test' %}" >テスト</a>
{% endblock %}

toppage/templates/toppage/test.html
{% extends "toppage/base.html" %}

{% block main %}
テストです。
{% endblock %}